### ISSUE TITLE
Requirements checking not clear

### ISSUE THREAD

**Issue by louis-cuny** [origamiphp/source#384]
In documentation/ getting started, it says I need mutagen
So, when I run origami --verbose, it should say "You need mutagen"

I already have docker, docker-compose & mkcert installed and have the corresponding checkmarks

**Comment by ajardin** [comment]
Hello @louis-cuny,

Could you share the output of `origami --verbose`?
On my side, I don't reproduce this behaviour on my local machine with the latest release. 😕

**Comment by louis-cuny** [comment]
I was on a old version because I didn't have php cli 8.0
Sorry for the noise
