### ISSUE TITLE
Inapropriate error on certificate creation

### ISSUE THREAD

**Issue by louis-cuny** [origamiphp/source#386]
My system doesnt not need any password for editing /etc/hosts

When I ask origami for creating a cert and a hostname, he seems to try twice to write in /etc/hosts and second time it throws an error:

 
Do you want to generate a locally-trusted development certificate? (yes/no) [no]:
 > yes

 Which domains does this certificate belong to? [knauf.test]:
 > 

                                                                                                                        
 [WARNING] Your hosts file do not contain the "127.0.0.1 knauf.test" entry.                                             
                                                                                                                        

 Do you want to automatically update it? Your password may be asked by the system, but you can also do it yourself afterwards. (yes/no) [no]:
 > yes

                                                                                                                        
 [ERROR] An environment with the same name already exists.

**Comment by duboiss** [comment]
Can you provide the content of your ~/.origami file?

**Comment by louis-cuny** [comment]
`[{"name":"knauf","location":"\/Users\/louis-cuny\/origami\/knauf","type":"magento2","domains":null,"active":true}]`

**Comment by ajardin** [comment]
Hello, and thanks for reporting this. 😉 

This behaviour should be fixed by https://github.com/origamiphp/source/pull/390 as we simplified the installation process and the management of self-signed certificates.
